.PHONY: clean-format

format_CFILES := $(shell find ./format/src -name "*.c")
format_BIN := obj/format/format

$(format_BIN): $(format_CFILES)
	@mkdir -p $(@D)
	@echo $^
	@gcc-4.9 -Wall -Werror -MMD -fno-builtin $^ -o $@ -Iformat/include

clean-format:
	@rm -rf obj/format
