kernel_EX_CFLAGS := -O0 -I$(LIB_COMMON_DIR)
kernel_EX_LDFLAGS := -e main -Ttext=0x100000
kernel_EX_RULES := bash fill.sh $$@ 102400

$(eval $(call make_common_rules,kernel,$(kernel_EX_CFLAGS),$(kernel_EX_LDFLAGS),$(LIB_COMMON),,$(kernel_EX_RULES)))

.PHNOY: clean-kernel

clean-kernel:
	@rm -rf $(kernel_OBJ_DIR)
