kernel_EX_CFLAGS := -O2 -I$(LIB_COMMON_DIR)
kernel_EX_LDFLAGS := -m elf_i386 -e _start -Ttext=0xc0100000

$(eval $(call make_common_rules,kernel,$(kernel_EX_CFLAGS),$(kernel_EX_LDFLAGS),$(LIB_COMMON)))
