idle_EX_CFLAGS := -O0 -I$(LIB_COMMON_DIR) -I$(LIB_APP_DIR)
idle_EX_LDFLAGS := -m elf_i386 -e _start
idle_EX_FILES_DEPENDED := $(LIB_COMMON) $(LIB_APP)

$(eval $(call make_common_rules,idle,$(idle_EX_CFLAGS),$(idle_EX_LDFLAGS),$(idle_EX_FILES_DEPENDED)))
